### ISSUE TITLE
Adding an option for specifying API mode

### ISSUE THREAD

**Issue by oyeanuj** [railsdiff/railsdiff#16]
Hi @jswanner, thank you for creating this excellent project! 

Curious if you'd consider adding an option for API mode since that is now [one of the main modes](https://guides.rubyonrails.org/api_app.html) promoted in the guides as well, and I assume a more common occurrence?

**Comment by nbibler** [comment]
With the released updates yesterday, the diff data is now backed by GitHub (see the [railsdiff/rails-new-output](https://github.com/railsdiff/rails-new-output) repository).

That said, you can use GitHub's interface to generate whatever you like, such as:

View the diff of v5.2.5 to v6.0.0 in the browser: https://github.com/railsdiff/rails-new-output/compare/v5.2.5..v6.0.0
Generate a raw diff: https://github.com/railsdiff/rails-new-output/compare/v5.2.5..v6.0.0.diff
Generate a patch: https://github.com/railsdiff/rails-new-output/compare/v5.2.5..v6.0.0.patch
etc.

The new browser client at https://railsdiff.org uses [GitHub's API](https://docs.github.com/en/rest/reference/repos#compare-two-commits) to perform similar diffs you can generate with the above URLs.
