### ISSUE TITLE
railsdiff.org is down, is this abandonned?

### ISSUE THREAD

**Issue by vmarquet** [railsdiff/railsdiff#17]
Thank you for this great project.

**Comment by jswanner** [comment]
It's not down for me currently and I haven't received any notifications from Uptime Robot, it's certainly not abandoned.

Are you still seeing the site as down? If so, what's the full URL you are using?

**Comment by vmarquet** [comment]
It's back up now. It was definitely down for me yesterday, I triple checked the url and used the link in your README. Go figure 🤷‍♂️

Thank you again for your work on this.

**Comment by jswanner** [comment]
Weird. Thanks for letting me know, none the less.

I'm glad you find it helpful.
