### ISSUE TITLE
Show default generated config for a specific version without diff? 

### ISSUE THREAD

**Issue by olivierlacan** [railsdiff/railsdiff#261]
Came up when trying to demonstrate that current Rails default mean that Heroku docs for Rails are inadequate because they suggest using [flags for puma in the Procfile](https://devcenter.heroku.com/articles/getting-started-with-rails7#create-a-procfile) when Rails has shipped with a `config/puma.rb` for years now.

Would have been neat to load something like `railsdiff.org/7.0.2.3/` or `railsdiff.org/defaults/7.0.2.3/` to see all default files for the given version.

**Comment by jswanner** [comment]
@olivierlacan, what do you think about linking to https://github.com/railsdiff/rails-new-output/tree/v7.0.2.3 somewhere?

**Comment by olivierlacan** [comment]
Seems super pragmatic and smart to me since the GitHub diff UI is great and familiar to many. 👍🏻

**Comment by nbibler** [comment]
I've added links to the footer of the compare view:

![output-links](https://user-images.githubusercontent.com/3775/183265729-9a90a75c-7bdc-4873-8bb0-849006e29e4d.png)

These link to the full GitHub version tree view for the selected versions.

❤️ @olivierlacan

**Comment by olivierlacan** [comment]
Ugh, lovely. 🤗
