### ISSUE TITLE
Download diff as a patch

### ISSUE THREAD

**Issue by liaden** [railsdiff/railsdiff#496]
It would be nice to be able to download the diff as a patch since that then allows for resolving conflicts through git when upgrading an app.

**Comment by jswanner** [comment]
@liaden, it's not linked to anywhere, nor documented, but you can use GitHub for this: https://github.com/railsdiff/rails-new-output/compare/v7.0.2.2...v7.0.2.3.diff

**Comment by henrikbjorn** [comment]
Was looking for this, a link would be awesome.

Then one could just `git apply` the diff :)

**Comment by airblade** [comment]
Adding to railsdiff.org a link to the patch would be super useful.

BTW I've used railsdiff.org for years and it has saved me so much time.  Thank you!  I really feel it should be recommended by the official Rails upgrade guide.
