### ISSUE TITLE
Broken due to GitHub API quota exhausted

### ISSUE THREAD

**Issue by andyw8** [railsdiff/railsdiff#582]
:wave:

I'm seeing only "Downloading and parsing available versions...".

The Chrome console shows:

> Request quota exhausted for request GET `https://api.github.com/repos/railsdiff/rails-new-output/tags?per_page=100`

**Comment by jswanner** [comment]
Well, that's fun...

/cc @nbibler

**Comment by nbibler** [comment]
From [Rate limits for the REST API](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-unauthenticated-users):

> The primary rate limit for unauthenticated requests is 60 requests per hour.

@andyw8: Had you somehow made more than 60 requests per hour to GitHub's API and/or are you on a proxied / corporate network sharing a single public IP with a larger group of individuals or machines?

The GitHub rate limits are unique to the person/browser calling the API. For RailsDiff, your browser is calling the API directly, so it's using your context (IP/browser/location) to load the data from the public GitHub repository.

**Comment by andyw8** [comment]
It happened on my first request, but I'm on a corporate network so it's possible others were also making requests.

**Comment by nbibler** [comment]
Yeah, I'm guessing (judging by your GitHub profile) that you're on Shopify's corporate network. I'll further assume they have an outbound proxy and that all requests from their corporate network look like the same IP address. You can test this by navigating to https://www.whatismyip.com/ and having another person on the network do the same, if you both get the same IP, that's what's going on.

If true, all of those requests look like they're coming from "the same person" to GitHub's API. So, it's certainly plausible in that case that 60+ requests had been made from other employees or automated systems within the network to GitHub's REST API.

**Comment by andyw8** [comment]
Yeah, makes sense. I'm wondering if there would be a simple way to set up a caching layer, e.g. the browser would make the request to `cache.railsdiff.org` instead of hitting `api.github.com` directly.

**Comment by nbibler** [comment]
It's certainly possible. But, managing and synchronizing an API cache from a 3rd party system for GitHub's repository state has some edge cases (when does invalidation occur, etc.).

Also, the current solution basically avoids RailsDiff paying for or maintaining any systems or services, which is 👍. 😄

**Comment by nbibler** [comment]
I can't say I'm terribly inclined to do too much here. At the moment, I'm leaning toward "this is a you problem" which happens to be currently showing itself for RailsDiff.

The solution should come from your corporate network maintainers, as it affects more than just RailsDiff. Presumably, anyone writing any scripts or queries against api.github.com will likely have the same problem.

I've also worked with other large companies with similar proxied networks who have run into the same problem when talking to Docker Hub, as an example. That service limits image pulls to 100 every 6 hours. When you're dealing with hundreds or thousands of engineers on a proxied network, many attempting to use Docker Compose, or running CI services, those 100 requests go quickly. 😁 

The solution in that example is to host an internal image cache. Seemingly, the same should be true here for Shopify (to host their own internal api.github.com proxy).

The costs of proxied networks. 🤷

**Comment by andyw8** [comment]
The irony is that we are already very heavy users of the GitHub's API, (and pay them lots of money!), but practically all of those other requests are authenticated, so have much higher limits.

I suppose one option would be to add a 'sign-in with GitHub' option to the site so that it used people's individual accounts, but I know that would be a lot of work for a small set of users.

I'll close the issue since there's nothing that can really be done at the moment.

**Comment by nbibler** [comment]
Yeah. It could have a dynamic connection to GitHub. 👍 That doesn't sound crazy but I haven't yet had a minute to think about it. 

I guess it would default to being anonymous to avoid people having to "sign in" to railsdiff. I know they're not, but it'd feel that way. 

Not a bad approach. I was just thinking that even if Shopify installed a local cache railsdiff would still have to be updated to make the endpoint dynamic.

This authenticate with GitHub approach is ultimately similar.
