### ISSUE TITLE
Update from 4.2.7.1 to 5.0 can't find action_cable

### ISSUE THREAD

**Issue by skiflink** [railsdiff/railsdiff#6]
After running rails update, adding all files included in the diff I am getting this error from within `cable.js`:

```
# Sprockets::FileNotFound:
      #   couldn't find file 'action_cable' with type 'application/javascript'
```

Even tried added `gem actioncable` and nothing.

**Comment by nbibler** [comment]
Did you `bundle update` after changing your `Gemfile` (specifically after changing `rails` to be `5.0.0`)? It looks like `actioncable` became a direct dependency of `rails` in `5.0.0`...

**Comment by jswanner** [comment]
I'm going to close this issue since it's so old, feel free to reopen if needed.
