### ISSUE TITLE
Add ability to view entire file

### ISSUE THREAD

**Issue by elsurudo** [railsdiff/railsdiff#7]
Sometimes when upgrading, you just want to take the entire file from the new Rails version. Perhaps simply a link to the raw file on github?

**Comment by jswanner** [comment]
I think it would be easier to use `rails app:update` (or `rake rails:update`) if you are just going to accept the new file unchanged.

**Comment by elsurudo** [comment]
Right, but if it's for only one file (as was the case for me), it's still nice to use the "railsdiff workflow", and simply have links to the raw files

**Comment by jswanner** [comment]
This has now been added and deployed.
